# Generated by Django 3.1 on 2020-08-20 21:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jokes', '0006_auto_20200820_1725'),
    ]

    operations = [
        migrations.RenameField(
            model_name='joke',
            old_name='tag',
            new_name='tags',
        ),
    ]
