# Generated by Django 3.1 on 2020-08-20 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jokes', '0007_auto_20200820_1733'),
    ]

    operations = [
        migrations.AlterField(
            model_name='joke',
            name='tags',
            field=models.ManyToManyField(blank=True, to='jokes.Tag'),
        ),
    ]
